import Config from 'react-native-config';

export const MEDIA_URL = Config.BRAND_MEDIA_URL;
export const AWS_PROJECT_REGION = Config.AWS_PROJECT_REGION;
export const AWS_APPSYNC_GRAPHQL_ENDPOINT = Config.AWS_APPSYNC_GRAPHQL_ENDPOINT;
export const AWS_APPSYNC_API_KEY = Config.AWS_APPSYNC_API_KEY;
export const AWS_COGNITO_IDENTITY_POOL_ID = Config.AWS_COGNITO_IDENTITY_POOL_ID;
export const AWS_COGNITO_REGION = Config.AWS_COGNITO_REGION;
export const AWS_USER_POOLS_ID = Config.AWS_USER_POOLS_ID;
export const AWS_USER_POOLS_WEB_CLIENT_ID = Config.AWS_USER_POOLS_WEB_CLIENT_ID;
export const AWS_USER_FILES_S3_BUCKET = Config.AWS_USER_FILES_S3_BUCKET;
export const AWS_USER_FILES_S3_BUCKET_REGION =
  Config.AWS_USER_FILES_S3_BUCKET_REGION;
export const WEBSITE_URL = Config.WEBSITE_URL;
export const INSTAGRAM_CLIENT_ID = Config.INSTAGRAM_CLIENT_ID;
export const INSTAGRAM_LOGIN_SCOPES = Config.INSTAGRAM_LOGIN_SCOPES;
export const RAZORPAY_MONTHLY_PLAN_ID =
  Config.NEXT_PUBLIC_RAZORPAY_MONTHLY_PLAN_ID;
export const RAZORPAY_ANNUAL_PLAN_ID =
  Config.NEXT_PUBLIC_RAZORPAY_ANNUAL_PLAN_ID;
export const RAZORPAY_KEY = Config.NEXT_PUBLIC_RAZORPAY_KEY;
